#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: e36a856
#
# Source0 file verified with key 0xD7574483BB57B18D (jr@jriddell.org)
#
Name     : kwin
Version  : 6.3.1
Release  : 151
URL      : https://download.kde.org/stable/plasma/6.3.1/kwin-6.3.1.tar.xz
Source0  : https://download.kde.org/stable/plasma/6.3.1/kwin-6.3.1.tar.xz
Source1  : https://download.kde.org/stable/plasma/6.3.1/kwin-6.3.1.tar.xz.sig
Source2  : D7574483BB57B18D.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0 MIT
Requires: kwin-bin = %{version}-%{release}
Requires: kwin-data = %{version}-%{release}
Requires: kwin-lib = %{version}-%{release}
Requires: kwin-license = %{version}-%{release}
Requires: kwin-locales = %{version}-%{release}
Requires: kwin-services = %{version}-%{release}
BuildRequires : attica-dev
BuildRequires : breeze
BuildRequires : breeze-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : clr-hardware-files
BuildRequires : extra-cmake-modules
BuildRequires : extra-cmake-modules-data
BuildRequires : freetype-dev
BuildRequires : glibc-dev
BuildRequires : gnupg
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kcrash-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kdecoration-dev
BuildRequires : kglobalaccel-dev
BuildRequires : kglobalacceld-dev
BuildRequires : ki18n-dev
BuildRequires : kidletime-dev
BuildRequires : kitemviews-dev
BuildRequires : kjobwidgets-dev
BuildRequires : kpipewire-dev
BuildRequires : kscreenlocker-dev
BuildRequires : kservice-dev
BuildRequires : kwayland-dev
BuildRequires : kwayland-server-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXau-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXdamage-dev
BuildRequires : libXdmcp-dev
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXi-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : libcanberra-dev
BuildRequires : libcap-dev
BuildRequires : libepoxy-dev
BuildRequires : libinput-dev
BuildRequires : libqaccessibilityclient-dev
BuildRequires : libxkbcommon-dev
BuildRequires : pciutils-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libdisplay-info)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libei-1.0)
BuildRequires : pkgconfig(libeis-1.0)
BuildRequires : pkgconfig(libpipewire-0.3)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libxcvt)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(x11-xcb)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xkbcommon-x11)
BuildRequires : plasma-activities-dev
BuildRequires : plasma-wayland-protocols-dev
BuildRequires : qt6base-dev
BuildRequires : qt6wayland-dev
BuildRequires : qtbase-staticdev
BuildRequires : solid-dev
BuildRequires : sonnet-dev
BuildRequires : systemd-dev
BuildRequires : wayland
BuildRequires : wayland-dev
BuildRequires : wayland-protocols
BuildRequires : wayland-protocols-dev
BuildRequires : xcb-util-cursor-dev
BuildRequires : xcb-util-dev
BuildRequires : xcb-util-image-dev
BuildRequires : xcb-util-keysyms-dev
BuildRequires : xcb-util-renderutil-dev
BuildRequires : xcb-util-wm-dev
BuildRequires : xcb-util-xrm-dev
BuildRequires : xwayland

%description
Aurorae is a themeable window decoration for KWin.
It supports theme files consisting of several SVG files for decoration and buttons. Themes can be
installed and selected directly in the configuration module of KWin decorations.

%package bin
Summary: bin components for the kwin package.
Group: Binaries
Requires: kwin-data = %{version}-%{release}
Requires: kwin-license = %{version}-%{release}
Requires: kwin-services = %{version}-%{release}

%description bin
bin components for the kwin package.


%package data
Summary: data components for the kwin package.
Group: Data

%description data
data components for the kwin package.


%package dev
Summary: dev components for the kwin package.
Group: Development
Requires: kwin-lib = %{version}-%{release}
Requires: kwin-bin = %{version}-%{release}
Requires: kwin-data = %{version}-%{release}
Provides: kwin-devel = %{version}-%{release}
Requires: kwin = %{version}-%{release}

%description dev
dev components for the kwin package.


%package doc
Summary: doc components for the kwin package.
Group: Documentation

%description doc
doc components for the kwin package.


%package lib
Summary: lib components for the kwin package.
Group: Libraries
Requires: kwin-data = %{version}-%{release}
Requires: kwin-license = %{version}-%{release}

%description lib
lib components for the kwin package.


%package license
Summary: license components for the kwin package.
Group: Default

%description license
license components for the kwin package.


%package locales
Summary: locales components for the kwin package.
Group: Default

%description locales
locales components for the kwin package.


%package services
Summary: services components for the kwin package.
Group: Systemd services
Requires: systemd

%description services
services components for the kwin package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) D7574483BB57B18D' gpg.status
%setup -q -n kwin-6.3.1
cd %{_builddir}/kwin-6.3.1
pushd ..
cp -a kwin-6.3.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739913690
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1739913690
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kwin
cp %{_builddir}/kwin-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/kwin/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/kwin-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kwin/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/kwin-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kwin/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/kwin-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kwin/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/kwin-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kwin/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/kwin-%{version}/LICENSES/GPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/kwin/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/kwin-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kwin/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kwin-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kwin/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kwin-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/kwin/3c3d7573e137d48253731c975ecf90d74cfa9efe || :
cp %{_builddir}/kwin-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/kwin/fa05e58320cb7c64786b26396f4b992579a628bc || :
cp %{_builddir}/kwin-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kwin/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
cp %{_builddir}/kwin-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kwin/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/kwin-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kwin/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/kwin-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kwin/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kwin-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kwin/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kwin-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/kwin/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3 || :
cp %{_builddir}/kwin-%{version}/examples/plugin/metadata.json.license %{buildroot}/usr/share/package-licenses/kwin/f9bb2e988a5b97ddfe98979cd3c3021017f5cbfd || :
cp %{_builddir}/kwin-%{version}/examples/quick-effect/package/contents/config/main.xml.license %{buildroot}/usr/share/package-licenses/kwin/f9bb2e988a5b97ddfe98979cd3c3021017f5cbfd || :
cp %{_builddir}/kwin-%{version}/examples/quick-effect/package/contents/ui/config.ui.license %{buildroot}/usr/share/package-licenses/kwin/f9bb2e988a5b97ddfe98979cd3c3021017f5cbfd || :
cp %{_builddir}/kwin-%{version}/examples/quick-effect/package/metadata.json.license %{buildroot}/usr/share/package-licenses/kwin/f9bb2e988a5b97ddfe98979cd3c3021017f5cbfd || :
cp %{_builddir}/kwin-%{version}/examples/quick-script/package/metadata.json.license %{buildroot}/usr/share/package-licenses/kwin/f9bb2e988a5b97ddfe98979cd3c3021017f5cbfd || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang kcm_kwindecoration
%find_lang kcm_kwinrules
%find_lang kcmkwm
%find_lang kwin
%find_lang kcm_kwin_effects
%find_lang kcm_kwin_scripts
%find_lang kcm_kwin_virtualdesktops
%find_lang kcm_kwintabbox
%find_lang kcm_kwinxwayland
%find_lang kcm_virtualkeyboard
%find_lang kcmkwincommon
%find_lang kcmkwincompositing
%find_lang kcmkwinscreenedges
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/kconf_update_bin/kwin-6.0-delete-desktop-switching-shortcuts
/V3/usr/lib64/kconf_update_bin/kwin-6.0-remove-breeze-tabbox-default
/V3/usr/lib64/kconf_update_bin/kwin-6.0-reset-active-mouse-screen
/V3/usr/lib64/kconf_update_bin/kwin-6.1-remove-gridview-expose-shortcuts
/V3/usr/lib64/kconf_update_bin/kwin5_update_default_rules
/V3/usr/lib64/libexec/kwin-applywindowdecoration
/V3/usr/lib64/libexec/kwin_killer_helper
/usr/lib64/kconf_update_bin/kwin-6.0-delete-desktop-switching-shortcuts
/usr/lib64/kconf_update_bin/kwin-6.0-remove-breeze-tabbox-default
/usr/lib64/kconf_update_bin/kwin-6.0-reset-active-mouse-screen
/usr/lib64/kconf_update_bin/kwin-6.1-remove-gridview-expose-shortcuts
/usr/lib64/kconf_update_bin/kwin5_update_default_rules
/usr/lib64/libexec/kwin-applywindowdecoration
/usr/lib64/libexec/kwin_killer_helper

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/kwin_wayland
/V3/usr/bin/kwin_wayland_wrapper
/V3/usr/bin/kwin_x11
/usr/bin/kwin_wayland
/usr/bin/kwin_wayland_wrapper
/usr/bin/kwin_x11

%files data
%defattr(-,root,root,-)
/usr/share/applications/kcm_kwin_effects.desktop
/usr/share/applications/kcm_kwin_scripts.desktop
/usr/share/applications/kcm_kwin_virtualdesktops.desktop
/usr/share/applications/kcm_kwindecoration.desktop
/usr/share/applications/kcm_kwinoptions.desktop
/usr/share/applications/kcm_kwinrules.desktop
/usr/share/applications/kcm_kwintabbox.desktop
/usr/share/applications/kcm_kwinxwayland.desktop
/usr/share/applications/kcm_virtualkeyboard.desktop
/usr/share/applications/kwincompositing.desktop
/usr/share/applications/org.kde.kwin.killer.desktop
/usr/share/config.kcfg/kwin.kcfg
/usr/share/config.kcfg/kwindecorationsettings.kcfg
/usr/share/config.kcfg/nightlightsettings.kcfg
/usr/share/config.kcfg/virtualdesktopssettings.kcfg
/usr/share/dbus-1/interfaces/org.kde.KWin.NightLight.xml
/usr/share/dbus-1/interfaces/org.kde.KWin.Plugins.xml
/usr/share/dbus-1/interfaces/org.kde.KWin.TabletModeManager.xml
/usr/share/dbus-1/interfaces/org.kde.KWin.VirtualDesktopManager.xml
/usr/share/dbus-1/interfaces/org.kde.KWin.xml
/usr/share/dbus-1/interfaces/org.kde.kwin.Compositing.xml
/usr/share/dbus-1/interfaces/org.kde.kwin.Effects.xml
/usr/share/dbus-1/interfaces/org.kde.kwin.InputDevice.xml
/usr/share/dbus-1/interfaces/org.kde.kwin.VirtualKeyboard.xml
/usr/share/icons/hicolor/16x16/apps/kwin.png
/usr/share/icons/hicolor/32x32/apps/kwin.png
/usr/share/icons/hicolor/48x48/apps/kwin.png
/usr/share/icons/hicolor/scalable/apps/kwin.svgz
/usr/share/kconf_update/kwin.upd
/usr/share/knotifications6/kwin.notifyrc
/usr/share/knsrcfiles/aurorae.knsrc
/usr/share/knsrcfiles/kwineffect.knsrc
/usr/share/knsrcfiles/kwinscripts.knsrc
/usr/share/knsrcfiles/kwinswitcher.knsrc
/usr/share/knsrcfiles/window-decorations.knsrc
/usr/share/krunner/dbusplugins/kwin-runner-windows.desktop
/usr/share/kwin/aurorae/AppMenuButton.qml
/usr/share/kwin/aurorae/AuroraeButton.qml
/usr/share/kwin/aurorae/AuroraeButtonGroup.qml
/usr/share/kwin/aurorae/AuroraeMaximizeButton.qml
/usr/share/kwin/aurorae/Decoration.qml
/usr/share/kwin/aurorae/DecorationButton.qml
/usr/share/kwin/aurorae/MenuButton.qml
/usr/share/kwin/aurorae/aurorae.qml
/usr/share/kwin/builtin-effects/blendchanges.json
/usr/share/kwin/builtin-effects/blur.json
/usr/share/kwin/builtin-effects/colorblindnesscorrection.json
/usr/share/kwin/builtin-effects/colorpicker.json
/usr/share/kwin/builtin-effects/contrast.json
/usr/share/kwin/builtin-effects/diminactive.json
/usr/share/kwin/builtin-effects/fallapart.json
/usr/share/kwin/builtin-effects/glide.json
/usr/share/kwin/builtin-effects/hidecursor.json
/usr/share/kwin/builtin-effects/highlightwindow.json
/usr/share/kwin/builtin-effects/invert.json
/usr/share/kwin/builtin-effects/kscreen.json
/usr/share/kwin/builtin-effects/magiclamp.json
/usr/share/kwin/builtin-effects/magnifier.json
/usr/share/kwin/builtin-effects/mouseclick.json
/usr/share/kwin/builtin-effects/mousemark.json
/usr/share/kwin/builtin-effects/outputlocator.json
/usr/share/kwin/builtin-effects/overview.json
/usr/share/kwin/builtin-effects/screenedge.json
/usr/share/kwin/builtin-effects/screenshot.json
/usr/share/kwin/builtin-effects/screentransform.json
/usr/share/kwin/builtin-effects/shakecursor.json
/usr/share/kwin/builtin-effects/sheet.json
/usr/share/kwin/builtin-effects/showcompositing.json
/usr/share/kwin/builtin-effects/showfps.json
/usr/share/kwin/builtin-effects/showpaint.json
/usr/share/kwin/builtin-effects/slide.json
/usr/share/kwin/builtin-effects/slideback.json
/usr/share/kwin/builtin-effects/slidingpopups.json
/usr/share/kwin/builtin-effects/snaphelper.json
/usr/share/kwin/builtin-effects/startupfeedback.json
/usr/share/kwin/builtin-effects/systembell.json
/usr/share/kwin/builtin-effects/thumbnailaside.json
/usr/share/kwin/builtin-effects/tileseditor.json
/usr/share/kwin/builtin-effects/touchpoints.json
/usr/share/kwin/builtin-effects/trackmouse.json
/usr/share/kwin/builtin-effects/windowview.json
/usr/share/kwin/builtin-effects/wobblywindows.json
/usr/share/kwin/builtin-effects/zoom.json
/usr/share/kwin/decorations/kwin4_decoration_qml_plastik/contents/config/main.xml
/usr/share/kwin/decorations/kwin4_decoration_qml_plastik/contents/ui/PlastikButton.qml
/usr/share/kwin/decorations/kwin4_decoration_qml_plastik/contents/ui/config.ui
/usr/share/kwin/decorations/kwin4_decoration_qml_plastik/contents/ui/main.qml
/usr/share/kwin/decorations/kwin4_decoration_qml_plastik/metadata.json
/usr/share/kwin/effects/dialogparent/contents/code/main.js
/usr/share/kwin/effects/dialogparent/metadata.json
/usr/share/kwin/effects/dimscreen/contents/code/main.js
/usr/share/kwin/effects/dimscreen/metadata.json
/usr/share/kwin/effects/eyeonscreen/contents/code/main.js
/usr/share/kwin/effects/eyeonscreen/metadata.json
/usr/share/kwin/effects/fade/contents/code/main.js
/usr/share/kwin/effects/fade/contents/config/main.xml
/usr/share/kwin/effects/fade/metadata.json
/usr/share/kwin/effects/fadedesktop/contents/code/main.js
/usr/share/kwin/effects/fadedesktop/metadata.json
/usr/share/kwin/effects/fadingpopups/contents/code/main.js
/usr/share/kwin/effects/fadingpopups/metadata.json
/usr/share/kwin/effects/frozenapp/contents/code/main.js
/usr/share/kwin/effects/frozenapp/metadata.json
/usr/share/kwin/effects/fullscreen/contents/code/main.js
/usr/share/kwin/effects/fullscreen/metadata.json
/usr/share/kwin/effects/login/contents/code/main.js
/usr/share/kwin/effects/login/contents/config/main.xml
/usr/share/kwin/effects/login/contents/ui/config.ui
/usr/share/kwin/effects/login/metadata.json
/usr/share/kwin/effects/logout/contents/code/main.js
/usr/share/kwin/effects/logout/metadata.json
/usr/share/kwin/effects/maximize/contents/code/main.js
/usr/share/kwin/effects/maximize/metadata.json
/usr/share/kwin/effects/outputlocator/qml/OutputLabel.qml
/usr/share/kwin/effects/scale/contents/code/main.js
/usr/share/kwin/effects/scale/contents/config/main.xml
/usr/share/kwin/effects/scale/contents/ui/config.ui
/usr/share/kwin/effects/scale/metadata.json
/usr/share/kwin/effects/sessionquit/contents/code/main.js
/usr/share/kwin/effects/sessionquit/metadata.json
/usr/share/kwin/effects/showcompositing/qml/main.qml
/usr/share/kwin/effects/showfps/qml/main-fallback.qml
/usr/share/kwin/effects/showfps/qml/main.qml
/usr/share/kwin/effects/squash/contents/code/main.js
/usr/share/kwin/effects/squash/metadata.json
/usr/share/kwin/effects/tileseditor/qml/ResizeCorner.qml
/usr/share/kwin/effects/tileseditor/qml/ResizeHandle.qml
/usr/share/kwin/effects/tileseditor/qml/TileDelegate.qml
/usr/share/kwin/effects/tileseditor/qml/layouts.svg
/usr/share/kwin/effects/tileseditor/qml/main.qml
/usr/share/kwin/effects/translucency/contents/code/main.js
/usr/share/kwin/effects/translucency/contents/config/main.xml
/usr/share/kwin/effects/translucency/contents/ui/config.ui
/usr/share/kwin/effects/translucency/metadata.json
/usr/share/kwin/effects/windowaperture/contents/code/main.js
/usr/share/kwin/effects/windowaperture/metadata.json
/usr/share/kwin/effects/windowview/qml/main.qml
/usr/share/kwin/frames/plasma/frame_none.qml
/usr/share/kwin/frames/plasma/frame_styled.qml
/usr/share/kwin/frames/plasma/frame_unstyled.qml
/usr/share/kwin/kcm_kwintabbox/desktop.png
/usr/share/kwin/kcm_kwintabbox/dolphin.png
/usr/share/kwin/kcm_kwintabbox/falkon.png
/usr/share/kwin/kcm_kwintabbox/kmail.png
/usr/share/kwin/kcm_kwintabbox/systemsettings.png
/usr/share/kwin/onscreennotification/plasma/dummydata/osd.qml
/usr/share/kwin/onscreennotification/plasma/main.qml
/usr/share/kwin/outline/plasma/outline.qml
/usr/share/kwin/scripts/desktopchangeosd/contents/ui/main.qml
/usr/share/kwin/scripts/desktopchangeosd/contents/ui/osd.qml
/usr/share/kwin/scripts/desktopchangeosd/metadata.json
/usr/share/kwin/scripts/minimizeall/contents/code/main.js
/usr/share/kwin/scripts/minimizeall/metadata.json
/usr/share/kwin/scripts/synchronizeskipswitcher/contents/code/main.js
/usr/share/kwin/scripts/synchronizeskipswitcher/metadata.json
/usr/share/kwin/scripts/videowall/contents/code/main.js
/usr/share/kwin/scripts/videowall/contents/config/main.xml
/usr/share/kwin/scripts/videowall/contents/ui/config.ui
/usr/share/kwin/scripts/videowall/metadata.json
/usr/share/kwin/tabbox/thumbnail_grid/contents/ui/main.qml
/usr/share/kwin/tabbox/thumbnail_grid/metadata.json
/usr/share/kwin/tm_inner.png
/usr/share/kwin/tm_outer.png
/usr/share/qlogging-categories6/org_kde_kwin.categories

%files dev
%defattr(-,root,root,-)
/usr/include/kwin/activities.h
/usr/include/kwin/appmenu.h
/usr/include/kwin/atoms.h
/usr/include/kwin/client_machine.h
/usr/include/kwin/compositor.h
/usr/include/kwin/config-kwin.h
/usr/include/kwin/core/colorlut3d.h
/usr/include/kwin/core/colorpipeline.h
/usr/include/kwin/core/colorpipelinestage.h
/usr/include/kwin/core/colorspace.h
/usr/include/kwin/core/colortransformation.h
/usr/include/kwin/core/drmdevice.h
/usr/include/kwin/core/gbmgraphicsbufferallocator.h
/usr/include/kwin/core/graphicsbuffer.h
/usr/include/kwin/core/graphicsbufferallocator.h
/usr/include/kwin/core/graphicsbufferview.h
/usr/include/kwin/core/iccprofile.h
/usr/include/kwin/core/inputbackend.h
/usr/include/kwin/core/inputdevice.h
/usr/include/kwin/core/output.h
/usr/include/kwin/core/outputbackend.h
/usr/include/kwin/core/outputconfiguration.h
/usr/include/kwin/core/outputlayer.h
/usr/include/kwin/core/overlaywindow.h
/usr/include/kwin/core/pixelgrid.h
/usr/include/kwin/core/renderbackend.h
/usr/include/kwin/core/renderjournal.h
/usr/include/kwin/core/renderlayer.h
/usr/include/kwin/core/renderlayerdelegate.h
/usr/include/kwin/core/renderloop.h
/usr/include/kwin/core/renderloop_p.h
/usr/include/kwin/core/rendertarget.h
/usr/include/kwin/core/renderviewport.h
/usr/include/kwin/core/session.h
/usr/include/kwin/core/session_consolekit.h
/usr/include/kwin/core/session_logind.h
/usr/include/kwin/core/session_noop.h
/usr/include/kwin/core/shmgraphicsbufferallocator.h
/usr/include/kwin/cursor.h
/usr/include/kwin/cursorsource.h
/usr/include/kwin/dbusinterface.h
/usr/include/kwin/debug_console.h
/usr/include/kwin/effect/animationeffect.h
/usr/include/kwin/effect/effect.h
/usr/include/kwin/effect/effecthandler.h
/usr/include/kwin/effect/effecttogglablestate.h
/usr/include/kwin/effect/effectwindow.h
/usr/include/kwin/effect/globals.h
/usr/include/kwin/effect/offscreeneffect.h
/usr/include/kwin/effect/offscreenquickview.h
/usr/include/kwin/effect/quickeffect.h
/usr/include/kwin/effect/timeline.h
/usr/include/kwin/effect/xcb.h
/usr/include/kwin/focuschain.h
/usr/include/kwin/ftrace.h
/usr/include/kwin/gestures.h
/usr/include/kwin/globalshortcuts.h
/usr/include/kwin/group.h
/usr/include/kwin/idle_inhibition.h
/usr/include/kwin/idledetector.h
/usr/include/kwin/input.h
/usr/include/kwin/input_event.h
/usr/include/kwin/input_event_spy.h
/usr/include/kwin/inputmethod.h
/usr/include/kwin/inputpanelv1integration.h
/usr/include/kwin/inputpanelv1window.h
/usr/include/kwin/internalwindow.h
/usr/include/kwin/keyboard_input.h
/usr/include/kwin/keyboard_layout.h
/usr/include/kwin/keyboard_layout_switching.h
/usr/include/kwin/keyboard_repeat.h
/usr/include/kwin/killwindow.h
/usr/include/kwin/kscreenintegration.h
/usr/include/kwin/kwin_export.h
/usr/include/kwin/layershellv1integration.h
/usr/include/kwin/layershellv1window.h
/usr/include/kwin/lidswitchtracker.h
/usr/include/kwin/main.h
/usr/include/kwin/mousebuttons.h
/usr/include/kwin/netinfo.h
/usr/include/kwin/onscreennotification.h
/usr/include/kwin/opengl/abstract_opengl_context_attribute_builder.h
/usr/include/kwin/opengl/egl_context_attribute_builder.h
/usr/include/kwin/opengl/eglcontext.h
/usr/include/kwin/opengl/egldisplay.h
/usr/include/kwin/opengl/eglimagetexture.h
/usr/include/kwin/opengl/eglnativefence.h
/usr/include/kwin/opengl/eglswapchain.h
/usr/include/kwin/opengl/eglutils_p.h
/usr/include/kwin/opengl/glframebuffer.h
/usr/include/kwin/opengl/gllut.h
/usr/include/kwin/opengl/gllut3D.h
/usr/include/kwin/opengl/glplatform.h
/usr/include/kwin/opengl/glrendertimequery.h
/usr/include/kwin/opengl/glshader.h
/usr/include/kwin/opengl/glshadermanager.h
/usr/include/kwin/opengl/gltexture.h
/usr/include/kwin/opengl/gltexture_p.h
/usr/include/kwin/opengl/glutils.h
/usr/include/kwin/opengl/glvertexbuffer.h
/usr/include/kwin/opengl/openglcontext.h
/usr/include/kwin/options.h
/usr/include/kwin/osd.h
/usr/include/kwin/outline.h
/usr/include/kwin/outputconfigurationstore.h
/usr/include/kwin/placeholderoutput.h
/usr/include/kwin/placement.h
/usr/include/kwin/placementtracker.h
/usr/include/kwin/plugin.h
/usr/include/kwin/pluginmanager.h
/usr/include/kwin/pointer_input.h
/usr/include/kwin/rulebooksettings.h
/usr/include/kwin/rules.h
/usr/include/kwin/scene/cursordelegate_opengl.h
/usr/include/kwin/scene/cursordelegate_qpainter.h
/usr/include/kwin/scene/cursoritem.h
/usr/include/kwin/scene/cursorscene.h
/usr/include/kwin/scene/decorationitem.h
/usr/include/kwin/scene/dndiconitem.h
/usr/include/kwin/scene/imageitem.h
/usr/include/kwin/scene/item.h
/usr/include/kwin/scene/itemgeometry.h
/usr/include/kwin/scene/itemrenderer.h
/usr/include/kwin/scene/itemrenderer_opengl.h
/usr/include/kwin/scene/itemrenderer_qpainter.h
/usr/include/kwin/scene/rootitem.h
/usr/include/kwin/scene/scene.h
/usr/include/kwin/scene/shadowitem.h
/usr/include/kwin/scene/surfaceitem.h
/usr/include/kwin/scene/surfaceitem_internal.h
/usr/include/kwin/scene/surfaceitem_wayland.h
/usr/include/kwin/scene/surfaceitem_x11.h
/usr/include/kwin/scene/windowitem.h
/usr/include/kwin/scene/workspacescene.h
/usr/include/kwin/scene/workspacescene_opengl.h
/usr/include/kwin/scene/workspacescene_qpainter.h
/usr/include/kwin/screenedge.h
/usr/include/kwin/screenlockerwatcher.h
/usr/include/kwin/shadow.h
/usr/include/kwin/sm.h
/usr/include/kwin/tablet_input.h
/usr/include/kwin/tabletmodemanager.h
/usr/include/kwin/touch_input.h
/usr/include/kwin/useractions.h
/usr/include/kwin/utils/c_ptr.h
/usr/include/kwin/utils/common.h
/usr/include/kwin/utils/cursortheme.h
/usr/include/kwin/utils/damagejournal.h
/usr/include/kwin/utils/drm_format_helper.h
/usr/include/kwin/utils/edid.h
/usr/include/kwin/utils/executable_path.h
/usr/include/kwin/utils/filedescriptor.h
/usr/include/kwin/utils/kernel.h
/usr/include/kwin/utils/memorymap.h
/usr/include/kwin/utils/orientationsensor.h
/usr/include/kwin/utils/ramfile.h
/usr/include/kwin/utils/realtime.h
/usr/include/kwin/utils/resource.h
/usr/include/kwin/utils/serviceutils.h
/usr/include/kwin/utils/softwarevsyncmonitor.h
/usr/include/kwin/utils/subsurfacemonitor.h
/usr/include/kwin/utils/udev.h
/usr/include/kwin/utils/version.h
/usr/include/kwin/utils/vsyncmonitor.h
/usr/include/kwin/utils/xcbutils.h
/usr/include/kwin/virtualdesktops.h
/usr/include/kwin/virtualdesktopsdbustypes.h
/usr/include/kwin/virtualkeyboard_dbus.h
/usr/include/kwin/wayland/alphamodifier_v1.h
/usr/include/kwin/wayland/appmenu.h
/usr/include/kwin/wayland/blur.h
/usr/include/kwin/wayland/clientconnection.h
/usr/include/kwin/wayland/compositor.h
/usr/include/kwin/wayland/contenttype_v1.h
/usr/include/kwin/wayland/contrast.h
/usr/include/kwin/wayland/cursorshape_v1.h
/usr/include/kwin/wayland/datacontroldevice_v1.h
/usr/include/kwin/wayland/datacontroldevicemanager_v1.h
/usr/include/kwin/wayland/datacontroloffer_v1.h
/usr/include/kwin/wayland/datacontrolsource_v1.h
/usr/include/kwin/wayland/datadevice.h
/usr/include/kwin/wayland/datadevicemanager.h
/usr/include/kwin/wayland/dataoffer.h
/usr/include/kwin/wayland/datasource.h
/usr/include/kwin/wayland/display.h
/usr/include/kwin/wayland/dpms.h
/usr/include/kwin/wayland/drmlease_v1.h
/usr/include/kwin/wayland/externalbrightness_v1.h
/usr/include/kwin/wayland/fractionalscale_v1.h
/usr/include/kwin/wayland/frog_colormanagement_v1.h
/usr/include/kwin/wayland/idle.h
/usr/include/kwin/wayland/idleinhibit_v1.h
/usr/include/kwin/wayland/idlenotify_v1.h
/usr/include/kwin/wayland/inputmethod_v1.h
/usr/include/kwin/wayland/keyboard.h
/usr/include/kwin/wayland/keyboard_shortcuts_inhibit_v1.h
/usr/include/kwin/wayland/keystate.h
/usr/include/kwin/wayland/layershell_v1.h
/usr/include/kwin/wayland/linux_drm_syncobj_v1.h
/usr/include/kwin/wayland/lockscreen_overlay_v1.h
/usr/include/kwin/wayland/output.h
/usr/include/kwin/wayland/output_order_v1.h
/usr/include/kwin/wayland/outputdevice_v2.h
/usr/include/kwin/wayland/outputmanagement_v2.h
/usr/include/kwin/wayland/plasmashell.h
/usr/include/kwin/wayland/plasmavirtualdesktop.h
/usr/include/kwin/wayland/plasmawindowmanagement.h
/usr/include/kwin/wayland/pointer.h
/usr/include/kwin/wayland/pointerconstraints_v1.h
/usr/include/kwin/wayland/pointergestures_v1.h
/usr/include/kwin/wayland/presentationtime.h
/usr/include/kwin/wayland/primaryselectiondevice_v1.h
/usr/include/kwin/wayland/primaryselectiondevicemanager_v1.h
/usr/include/kwin/wayland/primaryselectionoffer_v1.h
/usr/include/kwin/wayland/primaryselectionsource_v1.h
/usr/include/kwin/wayland/quirks.h
/usr/include/kwin/wayland/qwayland-server-alpha-modifier-v1.h
/usr/include/kwin/wayland/qwayland-server-content-type-v1.h
/usr/include/kwin/wayland/qwayland-server-frog-color-management-v1.h
/usr/include/kwin/wayland/qwayland-server-kde-external-brightness-v1.h
/usr/include/kwin/wayland/qwayland-server-linux-drm-syncobj-v1.h
/usr/include/kwin/wayland/qwayland-server-presentation-time.h
/usr/include/kwin/wayland/qwayland-server-xx-color-management-v4.h
/usr/include/kwin/wayland/relativepointer_v1.h
/usr/include/kwin/wayland/screencast_v1.h
/usr/include/kwin/wayland/screenedge_v1.h
/usr/include/kwin/wayland/seat.h
/usr/include/kwin/wayland/securitycontext_v1.h
/usr/include/kwin/wayland/server_decoration.h
/usr/include/kwin/wayland/server_decoration_palette.h
/usr/include/kwin/wayland/shadow.h
/usr/include/kwin/wayland/slide.h
/usr/include/kwin/wayland/subcompositor.h
/usr/include/kwin/wayland/surface.h
/usr/include/kwin/wayland/tablet_v2.h
/usr/include/kwin/wayland/tearingcontrol_v1.h
/usr/include/kwin/wayland/textinput_v1.h
/usr/include/kwin/wayland/textinput_v2.h
/usr/include/kwin/wayland/textinput_v3.h
/usr/include/kwin/wayland/touch.h
/usr/include/kwin/wayland/viewporter.h
/usr/include/kwin/wayland/wayland-alpha-modifier-v1-server-protocol.h
/usr/include/kwin/wayland/wayland-content-type-v1-server-protocol.h
/usr/include/kwin/wayland/wayland-frog-color-management-v1-server-protocol.h
/usr/include/kwin/wayland/wayland-kde-external-brightness-v1-server-protocol.h
/usr/include/kwin/wayland/wayland-linux-drm-syncobj-v1-server-protocol.h
/usr/include/kwin/wayland/wayland-presentation-time-server-protocol.h
/usr/include/kwin/wayland/wayland-xx-color-management-v4-server-protocol.h
/usr/include/kwin/wayland/xdgactivation_v1.h
/usr/include/kwin/wayland/xdgdecoration_v1.h
/usr/include/kwin/wayland/xdgdialog_v1.h
/usr/include/kwin/wayland/xdgforeign_v2.h
/usr/include/kwin/wayland/xdgoutput_v1.h
/usr/include/kwin/wayland/xdgshell.h
/usr/include/kwin/wayland/xdgsystembell_v1.h
/usr/include/kwin/wayland/xdgtoplevelicon_v1.h
/usr/include/kwin/wayland/xwaylandkeyboardgrab_v1.h
/usr/include/kwin/wayland/xwaylandshell_v1.h
/usr/include/kwin/wayland/xx_colormanagement_v4.h
/usr/include/kwin/wayland_server.h
/usr/include/kwin/waylandshellintegration.h
/usr/include/kwin/waylandwindow.h
/usr/include/kwin/window.h
/usr/include/kwin/workspace.h
/usr/include/kwin/x11eventfilter.h
/usr/include/kwin/x11window.h
/usr/include/kwin/xdgactivationv1.h
/usr/include/kwin/xdgshellintegration.h
/usr/include/kwin/xdgshellwindow.h
/usr/include/kwin/xkb.h
/usr/lib64/cmake/KWin/KWinConfig.cmake
/usr/lib64/cmake/KWin/KWinConfigVersion.cmake
/usr/lib64/cmake/KWin/KWinTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KWin/KWinTargets.cmake
/usr/lib64/cmake/KWinDBusInterface/KWinDBusInterfaceConfig.cmake
/usr/lib64/libkwin.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwindecoration/button.png
/usr/share/doc/HTML/ca/kcontrol/kwindecoration/decoration.png
/usr/share/doc/HTML/ca/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwindecoration/main.png
/usr/share/doc/HTML/ca/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/ca/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/ca/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/de/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/de/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/de/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/en/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwindecoration/button.png
/usr/share/doc/HTML/en/kcontrol/kwindecoration/configure.png
/usr/share/doc/HTML/en/kcontrol/kwindecoration/decoration.png
/usr/share/doc/HTML/en/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwindecoration/main.png
/usr/share/doc/HTML/en/kcontrol/kwineffects/configure-effects.png
/usr/share/doc/HTML/en/kcontrol/kwineffects/dialog-information.png
/usr/share/doc/HTML/en/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwineffects/video.png
/usr/share/doc/HTML/en/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwintabbox/taskswitcher.png
/usr/share/doc/HTML/en/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/en/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/en/kcontrol/windowspecific/Face-smile.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/akgregator-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/akregator-attributes.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/akregator-fav.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/config-win-behavior.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/emacs-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/emacs-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/focus-stealing-pop2top-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/en/kcontrol/windowspecific/knotes-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/knotes-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kopete-attribute-2.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kopete-chat-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kopete-chat-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kopete-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-detect-window.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-kopete-rules.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-rule-editor.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-rules-main-n-akregator.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-rules-main.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-rules-ordering.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-window-attributes.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-window-matching.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/pager-4-desktops.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-compose-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-compose-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-main-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-main-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-reminder-attribute-2.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-reminder-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-emacs.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-init.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-knotes.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-kopete-chat.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-kopete.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-ready-akregator.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-tbird-compose.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-tbird-main.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-tbird-reminder.png
/usr/share/doc/HTML/es/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/es/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/es/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/es/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/es/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/es/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/fr/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/fr/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/fr/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/fr/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/fr/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/id/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/id/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/id/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/id/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/id/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/id/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/id/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/it/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/it/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/it/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/nl/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/nl/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/nl/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/pt/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/pt/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/pt/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kwindecoration/configure.png
/usr/share/doc/HTML/pt_BR/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/ru/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/button.png
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/configure.png
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/decoration.png
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/main.png
/usr/share/doc/HTML/ru/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/ru/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/ru/kcontrol/windowspecific/akgregator-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/akregator-attributes.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/akregator-fav.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/config-win-behavior.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/emacs-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/emacs-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/focus-stealing-pop2top-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/ru/kcontrol/windowspecific/knotes-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/knotes-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kopete-attribute-2.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kopete-chat-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kopete-chat-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kopete-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-detect-window.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-kopete-rules.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-rule-editor.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-rules-main-n-akregator.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-rules-main.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-rules-ordering.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-window-attributes.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-window-matching.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-compose-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-compose-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-main-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-main-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-reminder-attribute-2.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-reminder-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-emacs.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-init.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-knotes.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-kopete-chat.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-kopete.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-ready-akregator.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-tbird-compose.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-tbird-main.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-tbird-reminder.png
/usr/share/doc/HTML/sl/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/sl/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/sl/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/sl/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/sl/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/sl/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/sl/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/sl/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/sl/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/sr/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/sv/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/sv/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/sv/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/tr/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/tr/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/tr/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/tr/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/tr/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/tr/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/tr/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/tr/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/tr/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/uk/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwindecoration/button.png
/usr/share/doc/HTML/uk/kcontrol/kwindecoration/decoration.png
/usr/share/doc/HTML/uk/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwindecoration/main.png
/usr/share/doc/HTML/uk/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/uk/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/uk/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/windowspecific/index.docbook

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libkcmkwincommon.so.6.3.1
/V3/usr/lib64/libkwin.so.6.3.1
/V3/usr/lib64/qt6/plugins/kf6/packagestructure/kwin_aurorae.so
/V3/usr/lib64/qt6/plugins/kf6/packagestructure/kwin_decoration.so
/V3/usr/lib64/qt6/plugins/kf6/packagestructure/kwin_effect.so
/V3/usr/lib64/qt6/plugins/kf6/packagestructure/kwin_scripts.so
/V3/usr/lib64/qt6/plugins/kf6/packagestructure/kwin_windowswitcher.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kcm_kwin4_genericscripted.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_blur_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_diminactive_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_glide_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_hidecursor_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_invert_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_magiclamp_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_magnifier_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_mouseclick_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_mousemark_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_overview_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_showpaint_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_slide_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_thumbnailaside_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_tileseditor_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_trackmouse_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_windowview_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_wobblywindows_config.so
/V3/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_zoom_config.so
/V3/usr/lib64/qt6/plugins/kwin/plugins/BounceKeysPlugin.so
/V3/usr/lib64/qt6/plugins/kwin/plugins/KeyNotificationPlugin.so
/V3/usr/lib64/qt6/plugins/kwin/plugins/StickyKeysPlugin.so
/V3/usr/lib64/qt6/plugins/kwin/plugins/buttonsrebind.so
/V3/usr/lib64/qt6/plugins/kwin/plugins/eis.so
/V3/usr/lib64/qt6/plugins/kwin/plugins/krunnerintegration.so
/V3/usr/lib64/qt6/plugins/kwin/plugins/nightlight.so
/V3/usr/lib64/qt6/plugins/kwin/plugins/screencast.so
/V3/usr/lib64/qt6/plugins/org.kde.kdecoration3.kcm/kcm_auroraedecoration.so
/V3/usr/lib64/qt6/plugins/org.kde.kdecoration3/org.kde.kwin.aurorae.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwin_effects.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwin_scripts.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwin_virtualdesktops.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwindecoration.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwinrules.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwinxwayland.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_virtualkeyboard.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwinoptions.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwinscreenedges.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwintabbox.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwintouchscreen.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kwincompositing.so
/V3/usr/lib64/qt6/qml/org/kde/kwin/decoration/libdecorationplugin.so
/V3/usr/lib64/qt6/qml/org/kde/kwin/decorations/plastik/libplastikplugin.so
/V3/usr/lib64/qt6/qml/org/kde/kwin/private/effects/libeffectsplugin.so
/V3/usr/lib64/qt6/qml/org/kde/kwin/private/kdecoration/libkdecorationprivatedeclarative.so
/usr/lib64/libkcmkwincommon.so.6
/usr/lib64/libkcmkwincommon.so.6.3.1
/usr/lib64/libkwin.so.6
/usr/lib64/libkwin.so.6.3.1
/usr/lib64/qt6/plugins/kf6/packagestructure/kwin_aurorae.so
/usr/lib64/qt6/plugins/kf6/packagestructure/kwin_decoration.so
/usr/lib64/qt6/plugins/kf6/packagestructure/kwin_effect.so
/usr/lib64/qt6/plugins/kf6/packagestructure/kwin_scripts.so
/usr/lib64/qt6/plugins/kf6/packagestructure/kwin_windowswitcher.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kcm_kwin4_genericscripted.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_blur_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_diminactive_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_glide_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_hidecursor_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_invert_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_magiclamp_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_magnifier_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_mouseclick_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_mousemark_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_overview_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_showpaint_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_slide_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_thumbnailaside_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_tileseditor_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_trackmouse_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_windowview_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_wobblywindows_config.so
/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_zoom_config.so
/usr/lib64/qt6/plugins/kwin/plugins/BounceKeysPlugin.so
/usr/lib64/qt6/plugins/kwin/plugins/KeyNotificationPlugin.so
/usr/lib64/qt6/plugins/kwin/plugins/StickyKeysPlugin.so
/usr/lib64/qt6/plugins/kwin/plugins/buttonsrebind.so
/usr/lib64/qt6/plugins/kwin/plugins/eis.so
/usr/lib64/qt6/plugins/kwin/plugins/krunnerintegration.so
/usr/lib64/qt6/plugins/kwin/plugins/nightlight.so
/usr/lib64/qt6/plugins/kwin/plugins/screencast.so
/usr/lib64/qt6/plugins/org.kde.kdecoration3.kcm/kcm_auroraedecoration.so
/usr/lib64/qt6/plugins/org.kde.kdecoration3/org.kde.kwin.aurorae.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwin_effects.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwin_scripts.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwin_virtualdesktops.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwindecoration.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwinrules.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_kwinxwayland.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings/kcm_virtualkeyboard.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwinoptions.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwinscreenedges.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwintabbox.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwintouchscreen.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kwincompositing.so
/usr/lib64/qt6/qml/org/kde/kwin/decoration/AppMenuButton.qml
/usr/lib64/qt6/qml/org/kde/kwin/decoration/ButtonGroup.qml
/usr/lib64/qt6/qml/org/kde/kwin/decoration/Decoration.qml
/usr/lib64/qt6/qml/org/kde/kwin/decoration/DecorationButton.qml
/usr/lib64/qt6/qml/org/kde/kwin/decoration/MenuButton.qml
/usr/lib64/qt6/qml/org/kde/kwin/decoration/libdecorationplugin.so
/usr/lib64/qt6/qml/org/kde/kwin/decoration/qmldir
/usr/lib64/qt6/qml/org/kde/kwin/decorations/plastik/libplastikplugin.so
/usr/lib64/qt6/qml/org/kde/kwin/decorations/plastik/qmldir
/usr/lib64/qt6/qml/org/kde/kwin/private/effects/WindowHeap.qml
/usr/lib64/qt6/qml/org/kde/kwin/private/effects/WindowHeapDelegate.qml
/usr/lib64/qt6/qml/org/kde/kwin/private/effects/effectsplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/kwin/private/effects/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/kwin/private/effects/libeffectsplugin.so
/usr/lib64/qt6/qml/org/kde/kwin/private/effects/qmldir
/usr/lib64/qt6/qml/org/kde/kwin/private/kdecoration/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/kwin/private/kdecoration/kdecorationprivatedeclarative.qmltypes
/usr/lib64/qt6/qml/org/kde/kwin/private/kdecoration/libkdecorationprivatedeclarative.so
/usr/lib64/qt6/qml/org/kde/kwin/private/kdecoration/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kwin/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/kwin/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/kwin/3c3d7573e137d48253731c975ecf90d74cfa9efe
/usr/share/package-licenses/kwin/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/kwin/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/kwin/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/kwin/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/kwin/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/kwin/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3
/usr/share/package-licenses/kwin/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/kwin/e712eadfab0d2357c0f50f599ef35ee0d87534cb
/usr/share/package-licenses/kwin/f9bb2e988a5b97ddfe98979cd3c3021017f5cbfd
/usr/share/package-licenses/kwin/fa05e58320cb7c64786b26396f4b992579a628bc

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/plasma-kwin_wayland.service
/usr/lib/systemd/user/plasma-kwin_x11.service

%files locales -f kcm_kwindecoration.lang -f kcm_kwinrules.lang -f kcmkwm.lang -f kwin.lang -f kcm_kwin_effects.lang -f kcm_kwin_scripts.lang -f kcm_kwin_virtualdesktops.lang -f kcm_kwintabbox.lang -f kcm_kwinxwayland.lang -f kcm_virtualkeyboard.lang -f kcmkwincommon.lang -f kcmkwincompositing.lang -f kcmkwinscreenedges.lang
%defattr(-,root,root,-)

