#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD7574483BB57B18D (jr@jriddell.org)
#
Name     : kwin
Version  : 5.25.2
Release  : 92
URL      : https://download.kde.org/stable/plasma/5.25.2/kwin-5.25.2.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.25.2/kwin-5.25.2.tar.xz
Source1  : https://download.kde.org/stable/plasma/5.25.2/kwin-5.25.2.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0 MIT
Requires: kwin-bin = %{version}-%{release}
Requires: kwin-data = %{version}-%{release}
Requires: kwin-filemap = %{version}-%{release}
Requires: kwin-lib = %{version}-%{release}
Requires: kwin-license = %{version}-%{release}
Requires: kwin-locales = %{version}-%{release}
Requires: kwin-services = %{version}-%{release}
BuildRequires : attica-dev
BuildRequires : breeze
BuildRequires : breeze-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : clr-hardware-files
BuildRequires : extra-cmake-modules pkgconfig(egl)
BuildRequires : extra-cmake-modules pkgconfig(wayland-client)
BuildRequires : extra-cmake-modules pkgconfig(x11-xcb)
BuildRequires : extra-cmake-modules qtwayland-dev
BuildRequires : extra-cmake-modules wayland
BuildRequires : extra-cmake-modules-data
BuildRequires : freetype-dev
BuildRequires : glibc-dev
BuildRequires : kactivities-dev
BuildRequires : kdecoration-dev
BuildRequires : kdoctools-dev
BuildRequires : kglobalaccel-dev
BuildRequires : ki18n-dev
BuildRequires : kidletime-dev
BuildRequires : kirigami2-dev
BuildRequires : kitemviews-dev
BuildRequires : kjobwidgets-dev
BuildRequires : krunner-dev
BuildRequires : kscreenlocker-dev
BuildRequires : kwayland-dev
BuildRequires : kwayland-server-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libcap-dev
BuildRequires : libepoxy-dev
BuildRequires : libinput-dev
BuildRequires : libxkbcommon-dev
BuildRequires : pciutils-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libpipewire-0.3)
BuildRequires : pkgconfig(libxcvt)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : plasma-framework-dev
BuildRequires : plasma-wayland-protocols-dev
BuildRequires : qt6base-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtbase-staticdev
BuildRequires : solid-dev
BuildRequires : sonnet-dev
BuildRequires : systemd-dev
BuildRequires : wayland-dev
BuildRequires : xcb-util-cursor-dev
BuildRequires : xcb-util-dev
BuildRequires : xcb-util-image-dev
BuildRequires : xcb-util-keysyms-dev
BuildRequires : xcb-util-renderutil-dev
BuildRequires : xcb-util-wm-dev
BuildRequires : xcb-util-xrm-dev
BuildRequires : xwayland

%description
Aurorae is a themeable window decoration for KWin.
It supports theme files consisting of several SVG files for decoration and buttons. Themes can be
installed and selected directly in the configuration module of KWin decorations.

%package bin
Summary: bin components for the kwin package.
Group: Binaries
Requires: kwin-data = %{version}-%{release}
Requires: kwin-license = %{version}-%{release}
Requires: kwin-services = %{version}-%{release}
Requires: kwin-filemap = %{version}-%{release}

%description bin
bin components for the kwin package.


%package data
Summary: data components for the kwin package.
Group: Data

%description data
data components for the kwin package.


%package dev
Summary: dev components for the kwin package.
Group: Development
Requires: kwin-lib = %{version}-%{release}
Requires: kwin-bin = %{version}-%{release}
Requires: kwin-data = %{version}-%{release}
Provides: kwin-devel = %{version}-%{release}
Requires: kwin = %{version}-%{release}

%description dev
dev components for the kwin package.


%package doc
Summary: doc components for the kwin package.
Group: Documentation

%description doc
doc components for the kwin package.


%package filemap
Summary: filemap components for the kwin package.
Group: Default

%description filemap
filemap components for the kwin package.


%package lib
Summary: lib components for the kwin package.
Group: Libraries
Requires: kwin-data = %{version}-%{release}
Requires: kwin-license = %{version}-%{release}
Requires: kwin-filemap = %{version}-%{release}

%description lib
lib components for the kwin package.


%package license
Summary: license components for the kwin package.
Group: Default

%description license
license components for the kwin package.


%package locales
Summary: locales components for the kwin package.
Group: Default

%description locales
locales components for the kwin package.


%package services
Summary: services components for the kwin package.
Group: Systemd services

%description services
services components for the kwin package.


%prep
%setup -q -n kwin-5.25.2
cd %{_builddir}/kwin-5.25.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656447029
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Wl,-z,x86-64-v3 -ffat-lto-objects -flto=auto -march=x86-64-v3 -msse2avx -mtune=skylake "
export FCFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -ffat-lto-objects -flto=auto -march=x86-64-v3 -msse2avx -mtune=skylake "
export FFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -ffat-lto-objects -flto=auto -march=x86-64-v3 -msse2avx -mtune=skylake "
export CXXFLAGS="$CXXFLAGS -O3 -Wl,-z,x86-64-v3 -ffat-lto-objects -flto=auto -march=x86-64-v3 -msse2avx -mtune=skylake "
export CFLAGS="$CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1656447029
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kwin
cp %{_builddir}/kwin-5.25.2/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/kwin/680ed9349d3d12bd39ddd36e8c4bc6b1b0cb1c0e
cp %{_builddir}/kwin-5.25.2/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/kwin/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
cp %{_builddir}/kwin-5.25.2/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kwin/2a638514c87c4923c0570c55822620fad56f2a33
cp %{_builddir}/kwin-5.25.2/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kwin/e712eadfab0d2357c0f50f599ef35ee0d87534cb
cp %{_builddir}/kwin-5.25.2/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kwin/6091db0aead0d90182b93d3c0d09ba93d188f907
cp %{_builddir}/kwin-5.25.2/LICENSES/GPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/kwin/6091db0aead0d90182b93d3c0d09ba93d188f907
cp %{_builddir}/kwin-5.25.2/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kwin/20079e8f79713dce80ab09774505773c926afa2a
cp %{_builddir}/kwin-5.25.2/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kwin/20079e8f79713dce80ab09774505773c926afa2a
cp %{_builddir}/kwin-5.25.2/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/kwin/3c3d7573e137d48253731c975ecf90d74cfa9efe
cp %{_builddir}/kwin-5.25.2/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kwin/757b86330df80f81143d5916b3e92b4bcb1b1890
cp %{_builddir}/kwin-5.25.2/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kwin/7d9831e05094ce723947d729c2a46a09d6e90275
cp %{_builddir}/kwin-5.25.2/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kwin/7d9831e05094ce723947d729c2a46a09d6e90275
cp %{_builddir}/kwin-5.25.2/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kwin/e458941548e0864907e654fa2e192844ae90fc32
cp %{_builddir}/kwin-5.25.2/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kwin/e458941548e0864907e654fa2e192844ae90fc32
cp %{_builddir}/kwin-5.25.2/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/kwin/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
%find_lang kcm_kwindecoration
%find_lang kcm_kwinrules
%find_lang kcmkwm
%find_lang kwin
%find_lang kwin_clients
%find_lang kcm-kwin-scripts
%find_lang kcm_kwin_effects
%find_lang kcm_kwin_virtualdesktops
%find_lang kcm_kwintabbox
%find_lang kcm_virtualkeyboard
%find_lang kcmkwincommon
%find_lang kcmkwincompositing
%find_lang kcmkwinscreenedges
%find_lang kwin_effects
%find_lang kwin_scripting
%find_lang kwin_scripts
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/kconf_update_bin/kwin5_update_default_rules
/usr/lib64/libexec/kwin-applywindowdecoration
/usr/lib64/libexec/kwin_killer_helper
/usr/lib64/libexec/kwin_rules_dialog

%files bin
%defattr(-,root,root,-)
/usr/bin/kwin_wayland
/usr/bin/kwin_wayland_wrapper
/usr/bin/kwin_x11
/usr/share/clear/optimized-elf/bin*

%files data
%defattr(-,root,root,-)
/usr/share/applications/kcm_kwin_effects.desktop
/usr/share/applications/kcm_kwin_scripts.desktop
/usr/share/applications/kcm_kwin_virtualdesktops.desktop
/usr/share/applications/kcm_kwindecoration.desktop
/usr/share/applications/kcm_kwinoptions.desktop
/usr/share/applications/kcm_kwinrules.desktop
/usr/share/applications/kcm_kwinscreenedges.desktop
/usr/share/applications/kcm_kwintouchscreen.desktop
/usr/share/applications/kcm_virtualkeyboard.desktop
/usr/share/applications/kwincompositing.desktop
/usr/share/applications/org.kde.kwin_rules_dialog.desktop
/usr/share/config.kcfg/kwin.kcfg
/usr/share/config.kcfg/kwin_colorcorrect.kcfg
/usr/share/config.kcfg/kwindecorationsettings.kcfg
/usr/share/config.kcfg/virtualdesktopssettings.kcfg
/usr/share/dbus-1/interfaces/org.kde.KWin.Plugins.xml
/usr/share/dbus-1/interfaces/org.kde.KWin.TabletModeManager.xml
/usr/share/dbus-1/interfaces/org.kde.KWin.VirtualDesktopManager.xml
/usr/share/dbus-1/interfaces/org.kde.KWin.xml
/usr/share/dbus-1/interfaces/org.kde.kwin.ColorCorrect.xml
/usr/share/dbus-1/interfaces/org.kde.kwin.Compositing.xml
/usr/share/dbus-1/interfaces/org.kde.kwin.Effects.xml
/usr/share/dbus-1/interfaces/org.kde.kwin.InputDevice.xml
/usr/share/dbus-1/interfaces/org.kde.kwin.VirtualKeyboard.xml
/usr/share/icons/hicolor/16x16/apps/kwin.png
/usr/share/icons/hicolor/32x32/apps/kwin.png
/usr/share/icons/hicolor/48x48/apps/kwin.png
/usr/share/icons/hicolor/scalable/apps/kwin.svgz
/usr/share/kconf_update/kwin-5.16-auto-bordersize.sh
/usr/share/kconf_update/kwin-5.18-move-animspeed.py
/usr/share/kconf_update/kwin-5.21-desktop-grid-click-behavior.py
/usr/share/kconf_update/kwin-5.21-no-swap-encourage.py
/usr/share/kconf_update/kwin-5.23-disable-translucency-effect.sh
/usr/share/kconf_update/kwin-5.23-remove-cover-switch.py
/usr/share/kconf_update/kwin-5.23-remove-cubeslide.py
/usr/share/kconf_update/kwin-5.23-remove-flip-switch.py
/usr/share/kconf_update/kwin-5.23-remove-xrender-backend.py
/usr/share/kconf_update/kwin-5.25-effect-pluginid-config-group.py
/usr/share/kconf_update/kwin.upd
/usr/share/kconf_update/kwinrules-5.19-placement.pl
/usr/share/kconf_update/kwinrules-5.23-virtual-desktop-ids.py
/usr/share/kconf_update/kwinrules.upd
/usr/share/knotifications5/kwin.notifyrc
/usr/share/knsrcfiles/aurorae.knsrc
/usr/share/knsrcfiles/kwineffect.knsrc
/usr/share/knsrcfiles/kwinscripts.knsrc
/usr/share/knsrcfiles/kwinswitcher.knsrc
/usr/share/knsrcfiles/window-decorations.knsrc
/usr/share/kpackage/kcms/kcm_kwin_effects/contents/ui/Effect.qml
/usr/share/kpackage/kcms/kcm_kwin_effects/contents/ui/Video.qml
/usr/share/kpackage/kcms/kcm_kwin_effects/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_kwin_effects/metadata.desktop
/usr/share/kpackage/kcms/kcm_kwin_effects/metadata.json
/usr/share/kpackage/kcms/kcm_kwin_scripts/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_kwin_virtualdesktops/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_kwin_virtualdesktops/metadata.desktop
/usr/share/kpackage/kcms/kcm_kwin_virtualdesktops/metadata.json
/usr/share/kpackage/kcms/kcm_kwindecoration/contents/ui/ButtonGroup.qml
/usr/share/kpackage/kcms/kcm_kwindecoration/contents/ui/Buttons.qml
/usr/share/kpackage/kcms/kcm_kwindecoration/contents/ui/Themes.qml
/usr/share/kpackage/kcms/kcm_kwindecoration/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_kwindecoration/metadata.desktop
/usr/share/kpackage/kcms/kcm_kwindecoration/metadata.json
/usr/share/kpackage/kcms/kcm_kwinrules/contents/ui/FileDialogLoader.qml
/usr/share/kpackage/kcms/kcm_kwinrules/contents/ui/OptionsComboBox.qml
/usr/share/kpackage/kcms/kcm_kwinrules/contents/ui/RuleItemDelegate.qml
/usr/share/kpackage/kcms/kcm_kwinrules/contents/ui/RulesEditor.qml
/usr/share/kpackage/kcms/kcm_kwinrules/contents/ui/RulesList.qml
/usr/share/kpackage/kcms/kcm_kwinrules/contents/ui/ValueEditor.qml
/usr/share/kpackage/kcms/kcm_kwinrules/metadata.desktop
/usr/share/kpackage/kcms/kcm_kwinrules/metadata.json
/usr/share/kpackage/kcms/kcm_virtualkeyboard/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_virtualkeyboard/metadata.desktop
/usr/share/kpackage/kcms/kcm_virtualkeyboard/metadata.json
/usr/share/krunner/dbusplugins/kwin-runner-windows.desktop
/usr/share/kservices5/kcm_kwintabbox.desktop
/usr/share/kservices5/kwin/kwin4_decoration_qml_plastik.desktop
/usr/share/kservicetypes5/kwindecoration.desktop
/usr/share/kservicetypes5/kwindesktopswitcher.desktop
/usr/share/kservicetypes5/kwineffect.desktop
/usr/share/kservicetypes5/kwinscript.desktop
/usr/share/kservicetypes5/kwinwindowswitcher.desktop
/usr/share/kwin/aurorae/AppMenuButton.qml
/usr/share/kwin/aurorae/AuroraeButton.qml
/usr/share/kwin/aurorae/AuroraeButtonGroup.qml
/usr/share/kwin/aurorae/AuroraeMaximizeButton.qml
/usr/share/kwin/aurorae/Decoration.qml
/usr/share/kwin/aurorae/DecorationButton.qml
/usr/share/kwin/aurorae/MenuButton.qml
/usr/share/kwin/aurorae/aurorae.qml
/usr/share/kwin/builtin-effects/kwin4_effect_blend/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_blur/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_colorpicker/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_contrast/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_desktopgrid/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_diminactive/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_fallapart/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_glide/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_highlightwindow/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_invert/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_kscreen/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_lookingglass/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_magiclamp/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_magnifier/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_mouseclick/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_mousemark/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_overview/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_screenedge/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_screenshot/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_screentransform/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_sheet/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_showfps/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_showpaint/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_slide/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_slideback/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_slidingpopups/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_snaphelper/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_startupfeedback/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_thumbnailaside/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_touchpoints/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_trackmouse/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_windowview/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_wobblywindows/metadata.json
/usr/share/kwin/builtin-effects/kwin4_effect_zoom/metadata.json
/usr/share/kwin/decorations/kwin4_decoration_qml_plastik/contents/config/main.xml
/usr/share/kwin/decorations/kwin4_decoration_qml_plastik/contents/ui/PlastikButton.qml
/usr/share/kwin/decorations/kwin4_decoration_qml_plastik/contents/ui/config.ui
/usr/share/kwin/decorations/kwin4_decoration_qml_plastik/contents/ui/main.qml
/usr/share/kwin/decorations/kwin4_decoration_qml_plastik/metadata.desktop
/usr/share/kwin/effects/desktopgrid/qml/DesktopView.qml
/usr/share/kwin/effects/desktopgrid/qml/main.qml
/usr/share/kwin/effects/kwin4_effect_dialogparent/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_dialogparent/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_dialogparent/metadata.json
/usr/share/kwin/effects/kwin4_effect_dimscreen/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_dimscreen/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_dimscreen/metadata.json
/usr/share/kwin/effects/kwin4_effect_eyeonscreen/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_eyeonscreen/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_eyeonscreen/metadata.json
/usr/share/kwin/effects/kwin4_effect_fade/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_fade/contents/config/main.xml
/usr/share/kwin/effects/kwin4_effect_fade/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_fade/metadata.json
/usr/share/kwin/effects/kwin4_effect_fadedesktop/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_fadedesktop/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_fadedesktop/metadata.json
/usr/share/kwin/effects/kwin4_effect_fadingpopups/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_fadingpopups/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_fadingpopups/metadata.json
/usr/share/kwin/effects/kwin4_effect_frozenapp/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_frozenapp/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_frozenapp/metadata.json
/usr/share/kwin/effects/kwin4_effect_fullscreen/contents/code/fullscreen.js
/usr/share/kwin/effects/kwin4_effect_fullscreen/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_fullscreen/metadata.json
/usr/share/kwin/effects/kwin4_effect_login/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_login/contents/config/main.xml
/usr/share/kwin/effects/kwin4_effect_login/contents/ui/config.ui
/usr/share/kwin/effects/kwin4_effect_login/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_login/metadata.json
/usr/share/kwin/effects/kwin4_effect_logout/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_logout/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_logout/metadata.json
/usr/share/kwin/effects/kwin4_effect_maximize/contents/code/maximize.js
/usr/share/kwin/effects/kwin4_effect_maximize/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_maximize/metadata.json
/usr/share/kwin/effects/kwin4_effect_morphingpopups/contents/code/morphingpopups.js
/usr/share/kwin/effects/kwin4_effect_morphingpopups/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_morphingpopups/metadata.json
/usr/share/kwin/effects/kwin4_effect_scale/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_scale/contents/config/main.xml
/usr/share/kwin/effects/kwin4_effect_scale/contents/ui/config.ui
/usr/share/kwin/effects/kwin4_effect_scale/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_scale/metadata.json
/usr/share/kwin/effects/kwin4_effect_sessionquit/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_sessionquit/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_sessionquit/metadata.json
/usr/share/kwin/effects/kwin4_effect_squash/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_squash/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_squash/metadata.json
/usr/share/kwin/effects/kwin4_effect_translucency/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_translucency/contents/config/main.xml
/usr/share/kwin/effects/kwin4_effect_translucency/contents/ui/config.ui
/usr/share/kwin/effects/kwin4_effect_translucency/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_translucency/metadata.json
/usr/share/kwin/effects/kwin4_effect_windowaperture/contents/code/main.js
/usr/share/kwin/effects/kwin4_effect_windowaperture/metadata.desktop
/usr/share/kwin/effects/kwin4_effect_windowaperture/metadata.json
/usr/share/kwin/effects/overview/qml/DesktopBar.qml
/usr/share/kwin/effects/overview/qml/DesktopView.qml
/usr/share/kwin/effects/overview/qml/ScreenView.qml
/usr/share/kwin/effects/windowview/qml/main.qml
/usr/share/kwin/frames/plasma/frame_none.qml
/usr/share/kwin/frames/plasma/frame_styled.qml
/usr/share/kwin/frames/plasma/frame_unstyled.qml
/usr/share/kwin/kcm_kwintabbox/desktop.png
/usr/share/kwin/kcm_kwintabbox/dolphin.png
/usr/share/kwin/kcm_kwintabbox/kmail.png
/usr/share/kwin/kcm_kwintabbox/konqueror.png
/usr/share/kwin/kcm_kwintabbox/systemsettings.png
/usr/share/kwin/onscreennotification/plasma/dummydata/osd.qml
/usr/share/kwin/onscreennotification/plasma/main.qml
/usr/share/kwin/outline/plasma/outline.qml
/usr/share/kwin/scripts/desktopchangeosd/contents/ui/main.qml
/usr/share/kwin/scripts/desktopchangeosd/contents/ui/osd.qml
/usr/share/kwin/scripts/desktopchangeosd/metadata.desktop
/usr/share/kwin/scripts/desktopchangeosd/metadata.json
/usr/share/kwin/scripts/minimizeall/contents/code/main.js
/usr/share/kwin/scripts/minimizeall/metadata.desktop
/usr/share/kwin/scripts/minimizeall/metadata.json
/usr/share/kwin/scripts/synchronizeskipswitcher/contents/code/main.js
/usr/share/kwin/scripts/synchronizeskipswitcher/metadata.desktop
/usr/share/kwin/scripts/synchronizeskipswitcher/metadata.json
/usr/share/kwin/scripts/videowall/contents/code/main.js
/usr/share/kwin/scripts/videowall/contents/config/main.xml
/usr/share/kwin/scripts/videowall/contents/ui/config.ui
/usr/share/kwin/scripts/videowall/metadata.desktop
/usr/share/kwin/scripts/videowall/metadata.json
/usr/share/kwin/tm_inner.png
/usr/share/kwin/tm_outer.png
/usr/share/qlogging-categories5/org_kde_kwin.categories

%files dev
%defattr(-,root,root,-)
/usr/include/kwin_export.h
/usr/include/kwinanimationeffect.h
/usr/include/kwinconfig.h
/usr/include/kwindeformeffect.h
/usr/include/kwineffects.h
/usr/include/kwineffects_export.h
/usr/include/kwinglobals.h
/usr/include/kwinglplatform.h
/usr/include/kwingltexture.h
/usr/include/kwinglutils.h
/usr/include/kwinglutils_export.h
/usr/include/kwinglutils_funcs.h
/usr/include/kwinoffscreenquickview.h
/usr/include/kwinquickeffect.h
/usr/include/kwinxrenderutils.h
/usr/include/kwinxrenderutils_export.h
/usr/lib64/cmake/KWinDBusInterface/KWinDBusInterfaceConfig.cmake
/usr/lib64/cmake/KWinEffects/KWinEffectsConfig.cmake
/usr/lib64/cmake/KWinEffects/KWinEffectsConfigVersion.cmake
/usr/lib64/cmake/KWinEffects/KWinEffectsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KWinEffects/KWinEffectsTargets.cmake
/usr/lib64/glibc-hwcaps/x86-64-v3/libkwineffects.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libkwinglutils.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libkwinxrenderutils.so
/usr/lib64/libkwineffects.so
/usr/lib64/libkwinglutils.so
/usr/lib64/libkwinxrenderutils.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwindecoration/button.png
/usr/share/doc/HTML/ca/kcontrol/kwindecoration/decoration.png
/usr/share/doc/HTML/ca/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwindecoration/main.png
/usr/share/doc/HTML/ca/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/ca/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/ca/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/de/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/de/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/de/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/de/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/en/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwindecoration/button.png
/usr/share/doc/HTML/en/kcontrol/kwindecoration/configure.png
/usr/share/doc/HTML/en/kcontrol/kwindecoration/decoration.png
/usr/share/doc/HTML/en/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwindecoration/main.png
/usr/share/doc/HTML/en/kcontrol/kwineffects/configure-effects.png
/usr/share/doc/HTML/en/kcontrol/kwineffects/dialog-information.png
/usr/share/doc/HTML/en/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwineffects/video.png
/usr/share/doc/HTML/en/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/en/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/en/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/en/kcontrol/windowspecific/Face-smile.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/akgregator-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/akregator-attributes.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/akregator-fav.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/config-win-behavior.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/emacs-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/emacs-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/focus-stealing-pop2top-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/en/kcontrol/windowspecific/knotes-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/knotes-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kopete-attribute-2.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kopete-chat-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kopete-chat-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kopete-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-detect-window.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-kopete-rules.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-rule-editor.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-rules-main-n-akregator.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-rules-main.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-rules-ordering.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-window-attributes.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/kwin-window-matching.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/pager-4-desktops.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-compose-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-compose-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-main-attribute.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-main-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-reminder-attribute-2.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/tbird-reminder-info.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-emacs.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-init.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-knotes.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-kopete-chat.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-kopete.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-ready-akregator.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-tbird-compose.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-tbird-main.png
/usr/share/doc/HTML/en/kcontrol/windowspecific/window-matching-tbird-reminder.png
/usr/share/doc/HTML/es/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/fr/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/fr/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/fr/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/fr/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/id/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/id/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/id/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/id/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/id/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/id/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/id/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/id/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/it/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/it/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/it/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/it/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/nl/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/nl/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/nl/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/pt/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/pt/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/pt/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kwindecoration/configure.png
/usr/share/doc/HTML/pt_BR/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/ru/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/button.png
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/configure.png
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/decoration.png
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwindecoration/main.png
/usr/share/doc/HTML/ru/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/ru/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/ru/kcontrol/windowspecific/akgregator-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/akregator-attributes.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/akregator-fav.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/config-win-behavior.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/emacs-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/emacs-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/focus-stealing-pop2top-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/ru/kcontrol/windowspecific/knotes-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/knotes-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kopete-attribute-2.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kopete-chat-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kopete-chat-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kopete-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-detect-window.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-kopete-rules.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-rule-editor.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-rules-main-n-akregator.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-rules-main.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-rules-ordering.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-window-attributes.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/kwin-window-matching.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-compose-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-compose-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-main-attribute.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-main-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-reminder-attribute-2.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/tbird-reminder-info.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-emacs.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-init.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-knotes.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-kopete-chat.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-kopete.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-ready-akregator.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-tbird-compose.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-tbird-main.png
/usr/share/doc/HTML/ru/kcontrol/windowspecific/window-matching-tbird-reminder.png
/usr/share/doc/HTML/sr/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/sv/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/sv/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/sv/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/windowspecific/index.docbook
/usr/share/doc/HTML/uk/kcontrol/desktop/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/desktop/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwindecoration/button.png
/usr/share/doc/HTML/uk/kcontrol/kwindecoration/decoration.png
/usr/share/doc/HTML/uk/kcontrol/kwindecoration/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwindecoration/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwindecoration/main.png
/usr/share/doc/HTML/uk/kcontrol/kwineffects/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwineffects/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwinscreenedges/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwinscreenedges/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwintabbox/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwintabbox/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwintouchscreen/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwintouchscreen/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kwinvirtualkeyboard/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kwinvirtualkeyboard/index.docbook
/usr/share/doc/HTML/uk/kcontrol/windowbehaviour/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/windowbehaviour/index.docbook
/usr/share/doc/HTML/uk/kcontrol/windowspecific/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/windowspecific/index.docbook

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-kwin

%files lib
%defattr(-,root,root,-)
/usr/lib64/glibc-hwcaps/x86-64-v3/libkcmkwincommon.so.5
/usr/lib64/glibc-hwcaps/x86-64-v3/libkcmkwincommon.so.5.25.2
/usr/lib64/glibc-hwcaps/x86-64-v3/libkwin.so.5
/usr/lib64/glibc-hwcaps/x86-64-v3/libkwin.so.5.25.2
/usr/lib64/glibc-hwcaps/x86-64-v3/libkwineffects.so.13
/usr/lib64/glibc-hwcaps/x86-64-v3/libkwineffects.so.5.25.2
/usr/lib64/glibc-hwcaps/x86-64-v3/libkwinglutils.so.13
/usr/lib64/glibc-hwcaps/x86-64-v3/libkwinglutils.so.5.25.2
/usr/lib64/glibc-hwcaps/x86-64-v3/libkwinxrenderutils.so.13
/usr/lib64/glibc-hwcaps/x86-64-v3/libkwinxrenderutils.so.5.25.2
/usr/lib64/libkcmkwincommon.so.5
/usr/lib64/libkcmkwincommon.so.5.25.2
/usr/lib64/libkwin.so.5
/usr/lib64/libkwin.so.5.25.2
/usr/lib64/libkwineffects.so.13
/usr/lib64/libkwineffects.so.5.25.2
/usr/lib64/libkwinglutils.so.13
/usr/lib64/libkwinglutils.so.5.25.2
/usr/lib64/libkwinxrenderutils.so.13
/usr/lib64/libkwinxrenderutils.so.5.25.2
/usr/lib64/qt5/plugins/kpackage/packagestructure/kwin_aurorae.so
/usr/lib64/qt5/plugins/kpackage/packagestructure/kwin_decoration.so
/usr/lib64/qt5/plugins/kpackage/packagestructure/kwin_effect.so
/usr/lib64/qt5/plugins/kpackage/packagestructure/kwin_script.so
/usr/lib64/qt5/plugins/kpackage/packagestructure/kwin_windowswitcher.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kcm_kwin4_genericscripted.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_blur_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_desktopgrid_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_diminactive_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_glide_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_invert_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_lookingglass_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_magiclamp_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_magnifier_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_mouseclick_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_mousemark_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_overview_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_showfps_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_showpaint_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_slide_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_thumbnailaside_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_trackmouse_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_windowview_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_wobblywindows_config.so
/usr/lib64/qt5/plugins/kwin/effects/configs/kwin_zoom_config.so
/usr/lib64/qt5/plugins/kwin/plugins/colordintegration.so
/usr/lib64/qt5/plugins/kwin/plugins/krunnerintegration.so
/usr/lib64/qt5/plugins/kwin/plugins/libKWinNightColorPlugin.so
/usr/lib64/qt5/plugins/org.kde.kdecoration2/kwin5_aurorae.so
/usr/lib64/qt5/plugins/org.kde.kwin.platforms/KWinX11Platform.so
/usr/lib64/qt5/plugins/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
/usr/lib64/qt5/plugins/org.kde.kwin.waylandbackends/KWinWaylandVirtualBackend.so
/usr/lib64/qt5/plugins/org.kde.kwin.waylandbackends/KWinWaylandWaylandBackend.so
/usr/lib64/qt5/plugins/org.kde.kwin.waylandbackends/KWinWaylandX11Backend.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_kwin_effects.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_kwin_scripts.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_kwin_virtualdesktops.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_kwindecoration.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_kwinrules.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings/kcm_virtualkeyboard.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwinoptions.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwinscreenedges.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwintabbox.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwintouchscreen.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/kwincompositing.so
/usr/lib64/qt5/qml/org/kde/kwin.2/DesktopThumbnailItem.qml
/usr/lib64/qt5/qml/org/kde/kwin.2/qmldir
/usr/lib64/qt5/qml/org/kde/kwin/decoration/AppMenuButton.qml
/usr/lib64/qt5/qml/org/kde/kwin/decoration/ButtonGroup.qml
/usr/lib64/qt5/qml/org/kde/kwin/decoration/Decoration.qml
/usr/lib64/qt5/qml/org/kde/kwin/decoration/DecorationButton.qml
/usr/lib64/qt5/qml/org/kde/kwin/decoration/MenuButton.qml
/usr/lib64/qt5/qml/org/kde/kwin/decoration/libdecorationplugin.so
/usr/lib64/qt5/qml/org/kde/kwin/decoration/qmldir
/usr/lib64/qt5/qml/org/kde/kwin/decorations/plastik/libplastikplugin.so
/usr/lib64/qt5/qml/org/kde/kwin/decorations/plastik/qmldir
/usr/lib64/qt5/qml/org/kde/kwin/private/effects/WindowHeap.qml
/usr/lib64/qt5/qml/org/kde/kwin/private/effects/WindowHeapDelegate.qml
/usr/lib64/qt5/qml/org/kde/kwin/private/effects/libeffectsplugin.so
/usr/lib64/qt5/qml/org/kde/kwin/private/effects/qmldir
/usr/lib64/qt5/qml/org/kde/kwin/private/kdecoration/libkdecorationprivatedeclarative.so
/usr/lib64/qt5/qml/org/kde/kwin/private/kdecoration/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kwin/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/kwin/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/kwin/3c3d7573e137d48253731c975ecf90d74cfa9efe
/usr/share/package-licenses/kwin/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/kwin/680ed9349d3d12bd39ddd36e8c4bc6b1b0cb1c0e
/usr/share/package-licenses/kwin/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/kwin/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/kwin/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/kwin/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3
/usr/share/package-licenses/kwin/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/kwin/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/plasma-kwin_wayland.service
/usr/lib/systemd/user/plasma-kwin_x11.service

%files locales -f kcm_kwindecoration.lang -f kcm_kwinrules.lang -f kcmkwm.lang -f kwin.lang -f kwin_clients.lang -f kcm-kwin-scripts.lang -f kcm_kwin_effects.lang -f kcm_kwin_virtualdesktops.lang -f kcm_kwintabbox.lang -f kcm_virtualkeyboard.lang -f kcmkwincommon.lang -f kcmkwincompositing.lang -f kcmkwinscreenedges.lang -f kwin_effects.lang -f kwin_scripting.lang -f kwin_scripts.lang
%defattr(-,root,root,-)

